POST http://localhost:8080/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "email": "test_1@sample.com",
    "password": "secret",
    "passwordAgain": "secret"
}


###

POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "test_1@sample.com",
    "password": "secret"
}

###

POST http://localhost:8080/api/auth/refresh-token HTTP/1.1
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNTA2MjNiNWYzZThlMzM0OGZiOTdjMSIsImVtYWlsIjoidGVzdF8xQHNhbXBsZS5jb20iLCJpYXQiOjE2MzI2NTk5ODUsImV4cCI6MTYzMzg2OTU4NX0.Jmh957xJV_09JBoT2O2TYCQb4CcHs8zY7_fGHeZylgk"
}

###

DELETE http://localhost:8080/api/auth/logout HTTP/1.1
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMzhiM2IxYjhkZWYxMGU3NDJhMmJjYiIsImVtYWlsIjoidGVzdF8zQHNhbXBsZS5jb20iLCJpYXQiOjE2MzExMTIyNzl9.sz7ikG0pSwBi9J3wI8hPwyWZfW6EBr34hfPciG12Ryg"
}

###

GET http://localhost:8080/secured HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RfM0BzYW1wbGUuY29tIiwiaWF0IjoxNjMxMTExMTI0LCJleHAiOjE2MzExMTExNTl9.oltg3P5azt-KRmp3KRT17l4mg5vSqbUg6B06Zqo-_iQ

###

GET http://localhost:8080/api/currencies HTTP/1.1
Content-Type: application/json

###

GET http://localhost:8080/api/budget HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNTA3YzlmZmNkYjFlM2FkYzA4Y2I0YiIsImVtYWlsIjoidGVzdF8xQHNhbXBsZS5jb20iLCJpYXQiOjE2MzI2NzEwOTksImV4cCI6MTYzMjY3Mjg5OX0.nHwpdhB4hne1jogSnXQ4WoRgs0FyD3i3bPd_Wauef2Q

###

GET http://localhost:8080/api/budget/accounts HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNTA3YzlmZmNkYjFlM2FkYzA4Y2I0YiIsImVtYWlsIjoidGVzdF8xQHNhbXBsZS5jb20iLCJpYXQiOjE2MzI2NzEwOTksImV4cCI6MTYzMjY3Mjg5OX0.nHwpdhB4hne1jogSnXQ4WoRgs0FyD3i3bPd_Wauef2Q

###

POST http://localhost:8080/api/budget HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNTA3YzlmZmNkYjFlM2FkYzA4Y2I0YiIsImVtYWlsIjoidGVzdF8xQHNhbXBsZS5jb20iLCJpYXQiOjE2MzI2NzEwOTksImV4cCI6MTYzMjY3Mjg5OX0.nHwpdhB4hne1jogSnXQ4WoRgs0FyD3i3bPd_Wauef2Q

{
    "accounts": [
        {
            "name": "main",
            "ammount": 21333,
            "currencyCode": "USD"
        } ,
        {
            "name": "savings",
            "ammount": 5000,
            "currencyCode": "USD"
        }
    ]
}