POST http://localhost:8080/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "email": "test_1@sample.com",
    "password": "secret",
    "passwordAgain": "secret"
}


###

POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "test@sample.com",
    "password": "secret"
}

###

POST http://localhost:8080/api/auth/refresh-token HTTP/1.1
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNzEyZjFhM2Y5ZGQzMDg0OGFkYWYxZiIsImVtYWlsIjoidGVzdEBzYW1wbGUuY29tIiwiaWF0IjoxNjM0ODE4NTU3LCJleHAiOjE2MzYwMjgxNTd9.GpZjwFJDeY1Yvji26p6-cfeXqQ37V1HKro4AKfaR1xs"
}

###

DELETE http://localhost:8080/api/auth/logout HTTP/1.1
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMzhiM2IxYjhkZWYxMGU3NDJhMmJjYiIsImVtYWlsIjoidGVzdF8zQHNhbXBsZS5jb20iLCJpYXQiOjE2MzExMTIyNzl9.sz7ikG0pSwBi9J3wI8hPwyWZfW6EBr34hfPciG12Ryg"
}

###

GET http://localhost:8080/api/currencies HTTP/1.1
Content-Type: application/json

###

GET http://localhost:8080/api/account HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNzEyZjFhM2Y5ZGQzMDg0OGFkYWYxZiIsImVtYWlsIjoidGVzdEBzYW1wbGUuY29tIiwiaWF0IjoxNjM0ODE4NTkxLCJleHAiOjE2MzQ4MjAzOTF9.kNq_Ksc-_D2tiHyuLCrjejg-l7nZZldqD-fUNuQLmDM

###

GET http://localhost:8080/api/history/61715a960a90884510c2ec9b HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNzEyZjFhM2Y5ZGQzMDg0OGFkYWYxZiIsImVtYWlsIjoidGVzdEBzYW1wbGUuY29tIiwiaWF0IjoxNjM0ODE4NTkxLCJleHAiOjE2MzQ4MjAzOTF9.kNq_Ksc-_D2tiHyuLCrjejg-l7nZZldqD-fUNuQLmDM