POST http://localhost:8080/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "email": "test_1@sample.com",
    "password": "secret",
    "passwordAgain": "secret"
}


###

POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "test@sample.com",
    "password": "secret"
}

###

POST http://localhost:8080/api/auth/refresh-token HTTP/1.1
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNTA2MjNiNWYzZThlMzM0OGZiOTdjMSIsImVtYWlsIjoidGVzdF8xQHNhbXBsZS5jb20iLCJpYXQiOjE2MzI2NTk5ODUsImV4cCI6MTYzMzg2OTU4NX0.Jmh957xJV_09JBoT2O2TYCQb4CcHs8zY7_fGHeZylgk"
}

###

DELETE http://localhost:8080/api/auth/logout HTTP/1.1
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMzhiM2IxYjhkZWYxMGU3NDJhMmJjYiIsImVtYWlsIjoidGVzdF8zQHNhbXBsZS5jb20iLCJpYXQiOjE2MzExMTIyNzl9.sz7ikG0pSwBi9J3wI8hPwyWZfW6EBr34hfPciG12Ryg"
}

###

GET http://localhost:8080/api/currencies HTTP/1.1
Content-Type: application/json

###

GET http://localhost:8080/api/account HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNTRkMzQ2NzU1ODMyM2EyNDFjNTAwNiIsImVtYWlsIjoidGVzdEBzYW1wbGUuY29tIiwiaWF0IjoxNjMyOTQ5NjU2LCJleHAiOjE2MzI5NTE0NTZ9.mZMzvTbHuTo1y9HInd8nAWM3IRW_oMQfLh0C2jfWYjQ

###

GET http://localhost:8080/api/account/6166f57efd696c1c68d8677c/history HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNjZmNTdlZmQ2OTZjMWM2OGQ4Njc3NSIsImVtYWlsIjoidGVzdEBzYW1wbGUuY29tIiwiaWF0IjoxNjM0MTQ4ODA3LCJleHAiOjE2MzQxNTA2MDd9.sVCX9T-msipo3v0p9YY181t0iSlWPrjLdMxMltg6ulk